In [51]:
pip install pandas numpy

Requirement already satisfied: pandas in c:\users\kamalesh kumar e c\desktop\sripriya\real estate\.venv\lib\site-packages (2.3.1)
Requirement already satisfied: numpy in c:\users\kamalesh kumar e c\desktop\sripriya\real estate\.venv\lib\site-packages (2.3.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\kamalesh kumar e c\desktop\sripriya\real estate\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\kamalesh kumar e c\desktop\sripriya\real estate\.venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\kamalesh kumar e c\desktop\sripriya\real estate\.venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\kamalesh kumar e c\desktop\sripriya\real estate\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [52]:
import pandas as pd
import numpy as np

In [53]:
Real_Estate_df = pd.read_csv('Luxury_Housing_Bangalore.csv')
Real_Estate_df

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
0,PROP000001,Sarjapur Road,Project_0,RMZ,4025.0,4bhk,12.750846039118798,Primary,NRI,2025-03-31,7.990091,5.462863,Launch,Broker,yes,9.212491,18,Loved the amenities!
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3Bhk,16.292151871065954,Primary,Other,2024-06-30,4.839024,NaN,Under construction,NRI Desk,no,7.723898,106,NaN
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4bhk,10.517724412961911,Primary,HNI,2023-12-31,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113,Agent was not responsive.
3,PROP000004,bellary road,Project_3,Embassy,6192.0,3BHK,9.396367494232896,Primary,HNI,2024-03-31,7.501657,5.720246,Ready to move,Online,yes,6.100929,106,Excellent location!
4,PROP000005,Koramangala,Project_4,SNN Raj,7147.0,4Bhk,15.345392444511946,Secondary,HNI,2024-12-31,4.525216,8.609649,Under construction,Broker,no,5.312510,18,Too far from my office.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100995,PROP004730,BELLARY ROAD,Project_229,Embassy,8546.0,5Bhk+,11.33081004147843,Secondary,CXO,2024-12-31,8.552797,6.221131,Under construction,NRI Desk,no,7.511827,22,Will buy after possession.
100996,PROP059810,Bellary Road,Project_309,Brigade,3408.0,3bhk,10.829373158307602,Primary,CXO,2024-09-30,6.879269,9.783611,Ready to move,Direct,no,9.851849,26,Agent was not responsive.
100997,PROP065099,HENNUR ROAD,Project_98,RMZ,4691.0,4BHK,11.183303152058548,Primary,NRI,2023-12-31,6.753812,8.383013,Under construction,Broker,no,9.101604,44,Loved the amenities!
100998,PROP093022,rajajinagar,Project_21,Embassy,7435.0,3BHK,10.914156376035923,Secondary,Other,2024-06-30,4.437787,5.756247,Under construction,Broker,yes,8.588551,66,Excellent location!
100999,PROP023826,whitefield,Project_325,L&T Realty,3218.0,4bhk,₹13.27 Cr,Primary,Startup Founder,2023-12-31,7.760416,9.989290,Under construction,Direct,yes,9.917647,58,Loved the amenities!

In [54]:
print(Real_Estate_df.head())

  Property_ID       Micro_Market Project_Name Developer_Name  Unit_Size_Sqft  \
0  PROP000001      Sarjapur Road    Project_0            RMZ          4025.0
1  PROP000002        Indiranagar    Project_1    Puravankara          5760.0
2  PROP000003  Bannerghatta Road    Project_2   Tata Housing          7707.0
3  PROP000004       bellary road    Project_3        Embassy          6192.0
4  PROP000005        Koramangala    Project_4        SNN Raj          7147.0

  Configuration     Ticket_Price_Cr Transaction_Type Buyer_Type  \
0          4bhk  12.750846039118798          Primary        NRI
1          3Bhk  16.292151871065954          Primary      Other
2          4bhk  10.517724412961911          Primary        HNI
3          3BHK   9.396367494232896          Primary        HNI
4          4Bhk  15.345392444511946        Secondary        HNI

  Purchase_Quarter  Connectivity_Score  Amenity_Score   Possession_Status  \
0       2025-03-31            7.990091       5.462863              Launch
1       2024-06-30            4.839024            NaN  Under construction
2       2023-12-31            8.131315       8.669227       Ready to move
3       2024-03-31            7.501657       5.720246       Ready to move
4       2024-12-31            4.525216       8.609649  Under construction

  Sales_Channel NRI_Buyer  Locality_Infra_Score  Avg_Traffic_Time_Min  \
0        Broker       yes              9.212491                    18
1      NRI Desk        no              7.723898                   106
2        Direct       yes              6.985493                   113
3        Online       yes              6.100929                   106
4        Broker        no              5.312510                    18

              Buyer_Comments
0       Loved the amenities!
1                        NaN
2  Agent was not responsive.
3        Excellent location!
4    Too far from my office.

In [55]:
print(Real_Estate_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101000 entries, 0 to 100999
Data columns (total 18 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           101000 non-null  object
 1   Micro_Market          101000 non-null  object
 2   Project_Name          101000 non-null  object
 3   Developer_Name        101000 non-null  object
 4   Unit_Size_Sqft        90954 non-null   float64
 5   Configuration         101000 non-null  object
 6   Ticket_Price_Cr       90981 non-null   object
 7   Transaction_Type      101000 non-null  object
 8   Buyer_Type            101000 non-null  object
 9   Purchase_Quarter      101000 non-null  object
 10  Connectivity_Score    101000 non-null  float64
 11  Amenity_Score         90910 non-null   float64
 12  Possession_Status     101000 non-null  object
 13  Sales_Channel         101000 non-null  object
 14  NRI_Buyer             101000 non-null  object
 15  Locality_Infra_Score  101000 non-null  float64
 16  Avg_Traffic_Time_Min  101000 non-null  int64
 17  Buyer_Comments        82713 non-null   object
dtypes: float64(4), int64(1), object(13)
memory usage: 13.9+ MB
None

In [56]:
def clean_ticket_price(Real_Estate_df):
    Real_Estate_df['Ticket_Price_Cr'] = (
        Real_Estate_df['Ticket_Price_Cr']
        .astype(str)
        .str.replace(',', '', regex=False)
        .str.extract(r'(\d+\.?\d*)')[0]  # Extract numeric part
        .astype(float)
    )
    return Real_Estate_df

In [57]:
def parse_purchase_quarter(Real_Estate_df):
    # If format is "Q1 2022"
    Real_Estate_df['Purchase_Quarter'] = pd.PeriodIndex(Real_Estate_df['Purchase_Quarter'], freq='Q')
    return Real_Estate_df

In [58]:
def convert_nri_flag(Real_Estate_df):
    Real_Estate_df['NRI_Buyer'] = Real_Estate_df['NRI_Buyer'].map({'Yes': True, 'No': False})
    return Real_Estate_df

In [59]:
def clean_property_data(Real_Estate_df):
    Real_Estate_df = clean_ticket_price(Real_Estate_df)
    Real_Estate_df = parse_purchase_quarter(Real_Estate_df)  # or convert_quarter_to_date(df)
    Real_Estate_df = convert_nri_flag(Real_Estate_df)
    return Real_Estate_df

In [60]:
print(Real_Estate_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101000 entries, 0 to 100999
Data columns (total 18 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           101000 non-null  object
 1   Micro_Market          101000 non-null  object
 2   Project_Name          101000 non-null  object
 3   Developer_Name        101000 non-null  object
 4   Unit_Size_Sqft        90954 non-null   float64
 5   Configuration         101000 non-null  object
 6   Ticket_Price_Cr       90981 non-null   object
 7   Transaction_Type      101000 non-null  object
 8   Buyer_Type            101000 non-null  object
 9   Purchase_Quarter      101000 non-null  object
 10  Connectivity_Score    101000 non-null  float64
 11  Amenity_Score         90910 non-null   float64
 12  Possession_Status     101000 non-null  object
 13  Sales_Channel         101000 non-null  object
 14  NRI_Buyer             101000 non-null  object
 15  Locality_Infra_Score  101000 non-null  float64
 16  Avg_Traffic_Time_Min  101000 non-null  int64
 17  Buyer_Comments        82713 non-null   object
dtypes: float64(4), int64(1), object(13)
memory usage: 13.9+ MB
None

In [61]:
Real_Estate_df['Configuration'] = Real_Estate_df['Configuration'].str.upper().str.strip()

In [62]:
Real_Estate_df['Configuration'] = Real_Estate_df['Configuration'].astype('category')

In [63]:
Real_Estate_df['NRI_Buyer'] = Real_Estate_df['NRI_Buyer'].str.lower().map({'yes': True, 'no': False})

In [64]:
Real_Estate_df['Amenity_Score'] = Real_Estate_df['Amenity_Score'].fillna(Real_Estate_df['Amenity_Score'].median())

In [65]:
Real_Estate_df['Amenity_Score_missing'] = Real_Estate_df['Amenity_Score'].isna().astype(int)

In [66]:
Real_Estate_df['Purchase_Quarter'] = pd.to_datetime(Real_Estate_df['Purchase_Quarter'], errors='coerce')

In [67]:
Real_Estate_df['Purchase_Year'] = Real_Estate_df['Purchase_Quarter'].dt.year
Real_Estate_df['Purchase_Qtr'] = Real_Estate_df['Purchase_Quarter'].dt.quarter

In [68]:
Real_Estate_df['Configuration'] = Real_Estate_df['Configuration'].str.lower().str.strip()

In [69]:
if not pd.api.types.is_datetime64_any_dtype(Real_Estate_df['Purchase_Quarter']):
    Real_Estate_df['Purchase_Quarter'] = pd.to_datetime(Real_Estate_df['Purchase_Quarter'], errors='coerce')

In [70]:
print(Real_Estate_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101000 entries, 0 to 100999
Data columns (total 21 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Property_ID            101000 non-null  object
 1   Micro_Market           101000 non-null  object
 2   Project_Name           101000 non-null  object
 3   Developer_Name         101000 non-null  object
 4   Unit_Size_Sqft         90954 non-null   float64
 5   Configuration          101000 non-null  object
 6   Ticket_Price_Cr        90981 non-null   object
 7   Transaction_Type       101000 non-null  object
 8   Buyer_Type             101000 non-null  object
 9   Purchase_Quarter       101000 non-null  datetime64[ns]
 10  Connectivity_Score     101000 non-null  float64
 11  Amenity_Score          101000 non-null  float64
 12  Possession_Status      101000 non-null  object
 13  Sales_Channel          101000 non-null  object
 14  NRI_Buyer              101000 non-null  bool
 15  Locality_Infra_Score   101000 non-null  float64
 16  Avg_Traffic_Time_Min   101000 non-null  int64
 17  Buyer_Comments         82713 non-null   object
 18  Amenity_Score_missing  101000 non-null  int64
 19  Purchase_Year          101000 non-null  int32
 20  Purchase_Qtr           101000 non-null  int32
dtypes: bool(1), datetime64[ns](1), float64(4), int32(2), int64(2), object(11)
memory usage: 14.7+ MB
None

In [71]:
Real_Estate_df[['Unit_Size_Sqft', 'Ticket_Price_Cr', 'Amenity_Score']].isnull().sum()

Unit_Size_Sqft     10046
Ticket_Price_Cr    10019
Amenity_Score          0
dtype: int64

In [72]:
Real_Estate_df.dropna(subset=['Unit_Size_Sqft', 'Ticket_Price_Cr'], inplace=True)

In [73]:
missing_summary = Real_Estate_df[Real_Estate_df['Unit_Size_Sqft'].isnull() | Real_Estate_df['Ticket_Price_Cr'].isnull()]
missing_by_market = missing_summary.groupby('Micro_Market').size().sort_values(ascending=False)
print(missing_by_market.head(10))

Series([], dtype: int64)

In [74]:
sales_by_qtr = Real_Estate_df.groupby(['Purchase_Year', 'Purchase_Qtr'])['Property_ID'].count().reset_index()
sales_by_qtr.rename(columns={'Property_ID': 'Transaction_Count'}, inplace=True)

In [75]:
Real_Estate_df['Ticket_Price_Cr'] = pd.to_numeric(Real_Estate_df['Ticket_Price_Cr'], errors='coerce')

In [76]:
Real_Estate_df_cleaned = Real_Estate_df.dropna(subset=['Ticket_Price_Cr'])

In [77]:
price_trend = Real_Estate_df_cleaned.groupby(
    ['Micro_Market', 'Purchase_Year', 'Purchase_Qtr']
)['Ticket_Price_Cr'].mean().reset_index()

In [78]:
assert pd.api.types.is_numeric_dtype(Real_Estate_df['Ticket_Price_Cr'])

In [79]:
print(Real_Estate_df['Ticket_Price_Cr'].dtype)

float64

In [80]:
price_trend = Real_Estate_df.groupby(['Micro_Market', 'Purchase_Year', 'Purchase_Qtr'])['Ticket_Price_Cr'].mean().reset_index()

In [81]:
buyer_mix = Real_Estate_df.groupby(['Purchase_Year', 'Purchase_Qtr', 'Buyer_Type'])['Property_ID'].count().reset_index()

In [82]:
Real_Estate_df['Unit_Size_Sqft'] = Real_Estate_df.groupby('Configuration')['Unit_Size_Sqft'].transform(
    lambda x: x.fillna(x.median())
)

Real_Estate_df['Ticket_Price_Cr'] = Real_Estate_df.groupby('Configuration')['Ticket_Price_Cr'].transform(
    lambda x: x.fillna(x.median())
)

In [83]:
Real_Estate_df['Unit_Size_Imputed'] = Real_Estate_df['Unit_Size_Sqft'].isna().astype(int)
Real_Estate_df['Ticket_Price_Imputed'] = Real_Estate_df['Ticket_Price_Cr'].isna().astype(int)

In [84]:
print(Real_Estate_df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 81884 entries, 0 to 100999
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Property_ID            81884 non-null  object
 1   Micro_Market           81884 non-null  object
 2   Project_Name           81884 non-null  object
 3   Developer_Name         81884 non-null  object
 4   Unit_Size_Sqft         81884 non-null  float64
 5   Configuration          81884 non-null  object
 6   Ticket_Price_Cr        81884 non-null  float64
 7   Transaction_Type       81884 non-null  object
 8   Buyer_Type             81884 non-null  object
 9   Purchase_Quarter       81884 non-null  datetime64[ns]
 10  Connectivity_Score     81884 non-null  float64
 11  Amenity_Score          81884 non-null  float64
 12  Possession_Status      81884 non-null  object
 13  Sales_Channel          81884 non-null  object
 14  NRI_Buyer              81884 non-null  bool
 15  Locality_Infra_Score   81884 non-null  float64
 16  Avg_Traffic_Time_Min   81884 non-null  int64
 17  Buyer_Comments         67111 non-null  object
 18  Amenity_Score_missing  81884 non-null  int64
 19  Purchase_Year          81884 non-null  int32
 20  Purchase_Qtr           81884 non-null  int32
 21  Unit_Size_Imputed      81884 non-null  int64
 22  Ticket_Price_Imputed   81884 non-null  int64
dtypes: bool(1), datetime64[ns](1), float64(5), int32(2), int64(4), object(10)
memory usage: 13.8+ MB
None

In [85]:
print(Real_Estate_df.head())

  Property_ID       Micro_Market Project_Name Developer_Name  Unit_Size_Sqft  \
0  PROP000001      Sarjapur Road    Project_0            RMZ          4025.0
1  PROP000002        Indiranagar    Project_1    Puravankara          5760.0
2  PROP000003  Bannerghatta Road    Project_2   Tata Housing          7707.0
3  PROP000004       bellary road    Project_3        Embassy          6192.0
4  PROP000005        Koramangala    Project_4        SNN Raj          7147.0

  Configuration  Ticket_Price_Cr Transaction_Type Buyer_Type Purchase_Quarter  \
0          4bhk        12.750846          Primary        NRI       2025-03-31
1          3bhk        16.292152          Primary      Other       2024-06-30
2          4bhk        10.517724          Primary        HNI       2023-12-31
3          3bhk         9.396367          Primary        HNI       2024-03-31
4          4bhk        15.345392        Secondary        HNI       2024-12-31

   ...  Sales_Channel  NRI_Buyer Locality_Infra_Score Avg_Traffic_Time_Min  \
0  ...         Broker       True             9.212491                   18
1  ...       NRI Desk      False             7.723898                  106
2  ...         Direct       True             6.985493                  113
3  ...         Online       True             6.100929                  106
4  ...         Broker      False             5.312510                   18

              Buyer_Comments  Amenity_Score_missing  Purchase_Year  \
0       Loved the amenities!                      0           2025
1                        NaN                      0           2024
2  Agent was not responsive.                      0           2023
3        Excellent location!                      0           2024
4    Too far from my office.                      0           2024

  Purchase_Qtr  Unit_Size_Imputed  Ticket_Price_Imputed
0            1                  0                     0
1            2                  0                     0
2            4                  0                     0
3            1                  0                     0
4            4                  0                     0

[5 rows x 23 columns]

In [86]:
Real_Estate_df[['Unit_Size_Sqft', 'Ticket_Price_Cr', 'Amenity_Score']].isnull().sum()

Unit_Size_Sqft     0
Ticket_Price_Cr    0
Amenity_Score      0
dtype: int64

In [87]:
Real_Estate_df

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,...,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments,Amenity_Score_missing,Purchase_Year,Purchase_Qtr,Unit_Size_Imputed,Ticket_Price_Imputed
0,PROP000001,Sarjapur Road,Project_0,RMZ,4025.0,4bhk,12.750846,Primary,NRI,2025-03-31,...,Broker,True,9.212491,18,Loved the amenities!,0,2025,1,0,0
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3bhk,16.292152,Primary,Other,2024-06-30,...,NRI Desk,False,7.723898,106,NaN,0,2024,2,0,0
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4bhk,10.517724,Primary,HNI,2023-12-31,...,Direct,True,6.985493,113,Agent was not responsive.,0,2023,4,0,0
3,PROP000004,bellary road,Project_3,Embassy,6192.0,3bhk,9.396367,Primary,HNI,2024-03-31,...,Online,True,6.100929,106,Excellent location!,0,2024,1,0,0
4,PROP000005,Koramangala,Project_4,SNN Raj,7147.0,4bhk,15.345392,Secondary,HNI,2024-12-31,...,Broker,False,5.312510,18,Too far from my office.,0,2024,4,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100995,PROP004730,BELLARY ROAD,Project_229,Embassy,8546.0,5bhk+,11.330810,Secondary,CXO,2024-12-31,...,NRI Desk,False,7.511827,22,Will buy after possession.,0,2024,4,0,0
100996,PROP059810,Bellary Road,Project_309,Brigade,3408.0,3bhk,10.829373,Primary,CXO,2024-09-30,...,Direct,False,9.851849,26,Agent was not responsive.,0,2024,3,0,0
100997,PROP065099,HENNUR ROAD,Project_98,RMZ,4691.0,4bhk,11.183303,Primary,NRI,2023-12-31,...,Broker,False,9.101604,44,Loved the amenities!,0,2023,4,0,0
100998,PROP093022,rajajinagar,Project_21,Embassy,7435.0,3bhk,10.914156,Secondary,Other,2024-06-30,...,Broker,True,8.588551,66,Excellent location!,0,2024,2,0,0
100999,PROP023826,whitefield,Project_325,L&T Realty,3218.0,4bhk,12.013659,Primary,Startup Founder,2023-12-31,...,Direct,True,9.917647,58,Loved the amenities!,0,2023,4,0,0

In [88]:
Real_Estate_df['Micro_Market'] = Real_Estate_df['Micro_Market'].str.title().str.strip()
Real_Estate_df['Configuration'] = Real_Estate_df['Configuration'].str.lower().str.replace('bhk', ' BHK')

In [89]:
Real_Estate_df['Buyer_Comments'] = Real_Estate_df['Buyer_Comments'].fillna('No comments provided')

In [90]:
Real_Estate_df['NRI_Buyer'] = Real_Estate_df['NRI_Buyer'].astype(bool)

In [91]:
assert Real_Estate_df['Unit_Size_Imputed'].isin([0, 1]).all()
assert Real_Estate_df['Ticket_Price_Imputed'].isin([0, 1]).all()

In [92]:
Real_Estate_df['Transaction_Type'] = Real_Estate_df['Transaction_Type'].fillna('Unknown')
Real_Estate_df['Buyer_Type'] = Real_Estate_df['Buyer_Type'].fillna('Unknown')

In [93]:
Real_Estate_df['Quarter_Label'] = 'Q' + Real_Estate_df['Purchase_Qtr'].astype(str) + ' ' + Real_Estate_df['Purchase_Year'].astype(str)

In [94]:
Real_Estate_df['Sales_Channel'] = Real_Estate_df['Sales_Channel'].str.title().str.strip()

In [95]:
Real_Estate_df

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,...,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments,Amenity_Score_missing,Purchase_Year,Purchase_Qtr,Unit_Size_Imputed,Ticket_Price_Imputed,Quarter_Label
0,PROP000001,Sarjapur Road,Project_0,RMZ,4025.0,4 BHK,12.750846,Primary,NRI,2025-03-31,...,True,9.212491,18,Loved the amenities!,0,2025,1,0,0,Q1 2025
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3 BHK,16.292152,Primary,Other,2024-06-30,...,False,7.723898,106,No comments provided,0,2024,2,0,0,Q2 2024
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4 BHK,10.517724,Primary,HNI,2023-12-31,...,True,6.985493,113,Agent was not responsive.,0,2023,4,0,0,Q4 2023
3,PROP000004,Bellary Road,Project_3,Embassy,6192.0,3 BHK,9.396367,Primary,HNI,2024-03-31,...,True,6.100929,106,Excellent location!,0,2024,1,0,0,Q1 2024
4,PROP000005,Koramangala,Project_4,SNN Raj,7147.0,4 BHK,15.345392,Secondary,HNI,2024-12-31,...,False,5.312510,18,Too far from my office.,0,2024,4,0,0,Q4 2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100995,PROP004730,Bellary Road,Project_229,Embassy,8546.0,5 BHK+,11.330810,Secondary,CXO,2024-12-31,...,False,7.511827,22,Will buy after possession.,0,2024,4,0,0,Q4 2024
100996,PROP059810,Bellary Road,Project_309,Brigade,3408.0,3 BHK,10.829373,Primary,CXO,2024-09-30,...,False,9.851849,26,Agent was not responsive.,0,2024,3,0,0,Q3 2024
100997,PROP065099,Hennur Road,Project_98,RMZ,4691.0,4 BHK,11.183303,Primary,NRI,2023-12-31,...,False,9.101604,44,Loved the amenities!,0,2023,4,0,0,Q4 2023
100998,PROP093022,Rajajinagar,Project_21,Embassy,7435.0,3 BHK,10.914156,Secondary,Other,2024-06-30,...,True,8.588551,66,Excellent location!,0,2024,2,0,0,Q2 2024
100999,PROP023826,Whitefield,Project_325,L&T Realty,3218.0,4 BHK,12.013659,Primary,Startup Founder,2023-12-31,...,True,9.917647,58,Loved the amenities!,0,2023,4,0,0,Q4 2023

In [96]:
pip install mysql.connector

Requirement already satisfied: mysql.connector in c:\users\kamalesh kumar e c\desktop\sripriya\real estate\.venv\lib\site-packages (2.2.9)
Note: you may need to restart the kernel to use updated packages.

In [97]:
pip install pymysql

Requirement already satisfied: pymysql in c:\users\kamalesh kumar e c\desktop\sripriya\real estate\.venv\lib\site-packages (1.1.1)
Note: you may need to restart the kernel to use updated packages.

In [98]:
pip install sqlalchemy

Requirement already satisfied: sqlalchemy in c:\users\kamalesh kumar e c\desktop\sripriya\real estate\.venv\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in c:\users\kamalesh kumar e c\desktop\sripriya\real estate\.venv\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\kamalesh kumar e c\desktop\sripriya\real estate\.venv\lib\site-packages (from sqlalchemy) (4.14.1)
Note: you may need to restart the kernel to use updated packages.

In [99]:
pip install cryptography

Requirement already satisfied: cryptography in c:\users\kamalesh kumar e c\desktop\sripriya\real estate\.venv\lib\site-packages (45.0.6)
Requirement already satisfied: cffi>=1.14 in c:\users\kamalesh kumar e c\desktop\sripriya\real estate\.venv\lib\site-packages (from cryptography) (1.17.1)
Requirement already satisfied: pycparser in c:\users\kamalesh kumar e c\desktop\sripriya\real estate\.venv\lib\site-packages (from cffi>=1.14->cryptography) (2.22)
Note: you may need to restart the kernel to use updated packages.

In [100]:
import pymysql
import pandas as pd

# Create connection
connection = pymysql.connect(

    host='localhost',        # or '127.0.0.1' or your DB server IP
    user='root',
    password='Harsha@123',
    database='realestate',
    port=3306                # default MySQL port
)

OperationalError: (1045, "Access denied for user 'root'@'localhost' (using password: YES)")

In [ ]:
from sqlalchemy import create_engine

In [ ]:
from sqlalchemy import text

with engine.connect() as conn:
    result = conn.execute(text("SELECT DATABASE();"))
    print("Connected to:", result.fetchone()[0])

Connected to: realestate

In [ ]:
Real_Estate_df.to_sql(name='real_estate', con=engine, if_exists='append', index=False)

81884

In [ ]:
engine = create_engine(
    "mysql+pymysql://root:Harshaa%40123@localhost:3306/realestate"
)